parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            #App:
            #    is_bundle: false
            #    type: annotation
            #    dir: '%kernel.project_dir%/src/Entity'
            #    prefix: 'App\Entity'
            #    alias: App
            Globale:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Globale/Entity'
                prefix: 'App\Modules\Globale\Entity'
            Share:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Share/Entity'
                prefix: 'App\Modules\Share\Entity'
            Email:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Email/Entity'
                prefix: 'App\Modules\Email\Entity'
            Calendar:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Calendar/Entity'
                prefix: 'App\Modules\Calendar\Entity'
            IoT:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/IoT/Entity'
                prefix: 'App\Modules\IoT\Entity'
            Ticketing:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Ticketing/Entity'
                prefix: 'App\Modules\Ticketing\Entity'
            HR:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/HR/Entity'
                prefix: 'App\Modules\HR\Entity'
            ERP:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/ERP/Entity'
                prefix: 'App\Modules\ERP\Entity'
            Carrier:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Carrier/Entity'
                prefix: 'App\Modules\Carrier\Entity'
            Cloud:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Modules/Cloud/Entity'
                prefix: 'App\Modules\Cloud\Entity'
