twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['form/boostrap.html.twig']
    paths:
        '%kernel.project_dir%/templates/twig': Twig
        '%kernel.project_dir%/src/Widgets': Widgets
        '%kernel.project_dir%/src/Modules/AERP/Templates': AERP
        '%kernel.project_dir%/src/Modules/HR/Templates': HR
        '%kernel.project_dir%/src/Modules/Cloud/Templates': Cloud
        '%kernel.project_dir%/src/Modules/Share/Templates': Share
        '%kernel.project_dir%/src/Modules/Email/Templates': Email
        '%kernel.project_dir%/src/Modules/Calendar/Templates': Calendar
        '%kernel.project_dir%/src/Modules/Globale/Templates': Globale
        '%kernel.project_dir%/src/Modules/Tracker/Templates': Tracker
        '%kernel.project_dir%/src/Modules/ERP/Templates': ERP
        '%kernel.project_dir%/src/Modules/Navision/Templates': Navision
        '%kernel.project_dir%/src/Modules/Vehicles/Templates': Vehicles
