# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
logout:
    path: /logout

Share:
    resource: 'App\Modules\Share\Controller\ShareController'
    type:     annotation

Email:
    resource: 'App\Modules\Email\Controller\EmailController'
    type:     annotation

Calendar:
    resource: 'App\Modules\Calendar\Controller\CalendarController'
    type:     annotation

Company:
    resource: 'App\Modules\Globale\Controller\GlobaleCompaniesController'
    type:     annotation

Entity:
    resource: 'App\Modules\ERP\Controller\ERPEntitiesController'
    type:     annotation

Customer:
    resource: 'App\Modules\ERP\Controller\ERPCustomersController'
    type:     annotation

CustomerGroups:
    resource: 'App\Modules\ERP\Controller\ERPCustomerGroupsController'
    type:     annotation

Supplier:
    resource: 'App\Modules\ERP\Controller\ERPSuppliersController'
    type:     annotation

Contacts:
    resource: 'App\Modules\ERP\Controller\ERPContactsController'
    type:     annotation

Addresses:
    resource: 'App\Modules\ERP\Controller\ERPAddressesController'
    type:     annotation

PaymentMethods:
    resource: 'App\Modules\ERP\Controller\ERPPaymentMethodsController'
    type:     annotation

Department:
    resource: 'App\Modules\ERP\Controller\ERPDepartmentsController'
    type:     annotation

BankAccount:
    resource: 'App\Modules\ERP\Controller\ERPBankAccountsController'
    type:     annotation

Manufacturer:
    resource: 'App\Modules\ERP\Controller\ERPManufacturersController'
    type:     annotation

Activity:
    resource: 'App\Modules\Globale\Controller\GlobaleActivitiesController'
    type:     annotation

Carrier:
    resource: 'App\Modules\Carrier\Controller\CarrierCarriersController'
    type:     annotation

ShippingCost:
    resource: 'App\Modules\Carrier\Controller\CarrierShippingCostsController'
    type:     annotation

Country:
    resource: 'App\Modules\Globale\Controller\GlobaleCountriesController'
    type:     annotation

Zone:
    resource: 'App\Modules\Carrier\Controller\CarrierZonesController'
    type:     annotation

State:
    resource: 'App\Modules\Globale\Controller\GlobaleStatesController'
    type:     annotation

Currency:
    resource: 'App\Modules\Globale\Controller\GlobaleCurrenciesController'
    type:     annotation

Dashboard:
    resource: 'App\Modules\Globale\Controller\GlobaleDashboardController'
    type:     annotation

Default:
    resource: 'App\Modules\Globale\Controller\GlobaleDefaultController'
    type:     annotation

File:
    resource: 'App\Modules\Globale\Controller\GlobaleFilesController'
    type:     annotation

Image:
    resource: 'App\Modules\Globale\Controller\GlobaleImagesController'
    type:     annotation

Notification:
    resource: 'App\Modules\Globale\Controller\GlobaleNotificationsController'
    type:     annotation

Security:
    resource: 'App\Modules\Globale\Controller\GlobaleSecurityController'
    type:     annotation

User:
    resource: 'App\Modules\Globale\Controller\GlobaleUsersController'
    type:     annotation

IoT:
    resource: 'App\Modules\IoT\Controller\IoTController'
    type:     annotation

HR:
   resource: 'App\Modules\HR\Controller\HRController'
   type:     annotation

HRHollidays:
   resource: 'App\Modules\HR\Controller\HRHollidaysController'
   type:     annotation

HRWorkCalendars:
   resource: 'App\Modules\HR\Controller\HRWorkCalendarsController'
   type:     annotation

HRClocks:
   resource: 'App\Modules\HR\Controller\HRClocksController'
   type:     annotation

Cloud:
   resource: 'App\Modules\Cloud\Controller\CloudController'
   type:     annotation

Tracker:
   resource: 'App\Modules\Tracker\Controller\TrackerTrackersController'
   type:     annotation

TrackerLocations:
   resource: 'App\Modules\Tracker\Controller\TrackerLocationsController'
   type:     annotation
