# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
logout:
    path: /logout

Share:
    resource: 'App\Modules\Share\Controller\ShareController'
    type:     annotation

Email:
    resource: 'App\Modules\Email\Controller\EmailController'
    type:     annotation

Calendar:
    resource: 'App\Modules\Calendar\Controller\CalendarController'
    type:     annotation

Permissions:
    resource: 'App\Modules\Globale\Controller\GlobalePermissionsController'
    type:     annotation

Company:
    resource: 'App\Modules\Globale\Controller\GlobaleCompaniesController'
    type:     annotation

ClockDevices:
    resource: 'App\Modules\Globale\Controller\GlobaleClockDevicesController'
    type:     annotation

ClockDevicesWorkers:
    resource: 'App\Modules\Globale\Controller\GlobaleClockDevicesWorkersController'
    type:     annotation

FirebaseDevices:
    resource: 'App\Modules\Globale\Controller\GlobaleFirebaseDevicesController'
    type:     annotation

Histories:
    resource: 'App\Modules\Globale\Controller\GlobaleHistoriesController'
    type:     annotation

Customer:
    resource: 'App\Modules\ERP\Controller\ERPCustomersController'
    type:     annotation

CustomerGroups:
    resource: 'App\Modules\ERP\Controller\ERPCustomerGroupsController'
    type:     annotation

CustomerSpecialConditions:
    resource: 'App\Modules\ERP\Controller\ERPCustomerSpecialConditionsController'
    type:     annotation

CustomerOrdersData:
    resource: 'App\Modules\ERP\Controller\ERPCustomerOrdersDataController'
    type:     annotation

CustomerCommercialTerms:
    resource: 'App\Modules\ERP\Controller\ERPCustomerCommercialTermsController'
    type:     annotation

CustomerCommentLines:
    resource: 'App\Modules\ERP\Controller\ERPCustomerCommentLinesController'
    type:     annotation

Increments:
    resource: 'App\Modules\ERP\Controller\ERPIncrementsController'
    type:     annotation

Supplier:
    resource: 'App\Modules\ERP\Controller\ERPSuppliersController'
    type:     annotation

SupplierActivities:
    resource: 'App\Modules\ERP\Controller\ERPSupplierActivitiesController'
    type:     annotation

SupplierOrdersData:
    resource: 'App\Modules\ERP\Controller\ERPSupplierOrdersDataController'
    type:     annotation

SupplierCommentLines:
    resource: 'App\Modules\ERP\Controller\ERPSupplierCommentLinesController'
    type:     annotation

EAN13:
    resource: 'App\Modules\ERP\Controller\ERPEAN13Controller'
    type:     annotation

Categories:
    resource: 'App\Modules\ERP\Controller\ERPCategoriesController'
    type:     annotation

References:
    resource: 'App\Modules\ERP\Controller\ERPReferencesController'
    type:     annotation

Contacts:
    resource: 'App\Modules\ERP\Controller\ERPContactsController'
    type:     annotation

Addresses:
    resource: 'App\Modules\ERP\Controller\ERPAddressesController'
    type:     annotation

PaymentMethods:
    resource: 'App\Modules\ERP\Controller\ERPPaymentMethodsController'
    type:     annotation

BankAccount:
    resource: 'App\Modules\ERP\Controller\ERPBankAccountsController'
    type:     annotation

Manufacturer:
    resource: 'App\Modules\ERP\Controller\ERPManufacturersController'
    type:     annotation

Product:
    resource: 'App\Modules\ERP\Controller\ERPProductsController'
    type:     annotation

ProductPrices:
    resource: 'App\Modules\ERP\Controller\ERPProductPricesController'
    type:     annotation

OfferPrices:
    resource: 'App\Modules\ERP\Controller\ERPOfferPricesController'
    type:     annotation

MeasurementUnits:
    resource: 'App\Modules\ERP\Controller\ERPMeasurementUnitsController'
    type:     annotation

WebProduct:
    resource: 'App\Modules\ERP\Controller\ERPWebProductsController'
    type:     annotation

Store:
    resource: 'App\Modules\ERP\Controller\ERPStoresController'
    type:     annotation

StoreLocation:
    resource: 'App\Modules\ERP\Controller\ERPStoreLocationsController'
    type:     annotation

Stock:
    resource: 'App\Modules\ERP\Controller\ERPStocksController'
    type:     annotation

PlazaVouchers:
  resource: 'App\Modules\ERP\Controller\ERPPlazaVouchersController'
  type:      annotation

Activity:
    resource: 'App\Modules\Globale\Controller\GlobaleActivitiesController'
    type:     annotation

Carrier:
    resource: 'App\Modules\Carrier\Controller\CarrierCarriersController'
    type:     annotation

ShippingCost:
    resource: 'App\Modules\Carrier\Controller\CarrierShippingCostsController'
    type:     annotation

Country:
    resource: 'App\Modules\Globale\Controller\GlobaleCountriesController'
    type:     annotation

Zone:
    resource: 'App\Modules\Carrier\Controller\CarrierZonesController'
    type:     annotation

State:
    resource: 'App\Modules\Globale\Controller\GlobaleStatesController'
    type:     annotation

Currency:
    resource: 'App\Modules\Globale\Controller\GlobaleCurrenciesController'
    type:     annotation

Dashboard:
    resource: 'App\Modules\Globale\Controller\GlobaleDashboardController'
    type:     annotation

Default:
    resource: 'App\Modules\Globale\Controller\GlobaleDefaultController'
    type:     annotation

File:
    resource: 'App\Modules\Globale\Controller\GlobaleFilesController'
    type:     annotation

Image:
    resource: 'App\Modules\Globale\Controller\GlobaleImagesController'
    type:     annotation

Notification:
    resource: 'App\Modules\Globale\Controller\GlobaleNotificationsController'
    type:     annotation

Security:
    resource: 'App\Modules\Globale\Controller\GlobaleSecurityController'
    type:     annotation

User:
    resource: 'App\Modules\Globale\Controller\GlobaleUsersController'
    type:     annotation

IoT:
    resource: 'App\Modules\IoT\Controller\IoTController'
    type:     annotation

HR:
   resource: 'App\Modules\HR\Controller\HRController'
   type:     annotation

HRHollidays:
   resource: 'App\Modules\HR\Controller\HRHollidaysController'
   type:     annotation

HRWorkCalendars:
   resource: 'App\Modules\HR\Controller\HRWorkCalendarsController'
   type:     annotation

HRClocks:
   resource: 'App\Modules\HR\Controller\HRClocksController'
   type:     annotation

HRDepartments:
   resource: 'App\Modules\HR\Controller\HRDepartmentsController'
   type:     annotation

HRVacations:
   resource: 'App\Modules\HR\Controller\HRVacationsController'
   type:     annotation

HRLaborAgreements:
   resource: 'App\Modules\HR\Controller\HRLaborAgreementsController'
   type:     annotation

HRSickleaves:
   resource: 'App\Modules\HR\Controller\HRSickleavesController'
   type:     annotation

HRJobs:
   resource: 'App\Modules\HR\Controller\HRJobsController'
   type:     annotation

HRWorkCenter:
   resource: 'App\Modules\HR\Controller\HRWorkCentersController'
   type:     annotation

HRSchedules:
   resource: 'App\Modules\HR\Controller\HRSchedulesController'
   type:     annotation

HRShifts:
   resource: 'App\Modules\HR\Controller\HRShiftsController'
   type:     annotation

HRPeriods:
   resource: 'App\Modules\HR\Controller\HRPeriodsController'
   type:     annotation

HREquipmentsController:
   resource: 'App\Modules\HR\Controller\HREquipmentsController'
   type:     annotation

Cloud:
   resource: 'App\Modules\Cloud\Controller\CloudController'
   type:     annotation

Tracker:
   resource: 'App\Modules\Tracker\Controller\TrackerTrackersController'
   type:     annotation

TrackerLocations:
   resource: 'App\Modules\Tracker\Controller\TrackerLocationsController'
   type:     annotation

Widgets:
  resource: 'App\Modules\Globale\Controller\GlobaleWidgetsController'
  type:     annotation

Navision:
  resource: 'App\Modules\Navision\Controller\NavisionController'
  type:     annotation

AERPCustomer:
  resource: 'App\Modules\AERP\Controller\AERPCustomersController'
  type:      annotation

AERPProvider:
  resource: 'App\Modules\AERP\Controller\AERPProvidersController'
  type:      annotation

AERPCategories:
  resource: 'App\Modules\AERP\Controller\AERPCategoriesController'
  type:      annotation

AERPProducts:
  resource: 'App\Modules\AERP\Controller\AERPProductsController'
  type:      annotation

AERPSalesBudgets:
  resource: 'App\Modules\AERP\Controller\AERPSalesBudgetsController'
  type:      annotation

AERPSalesOrders:
  resource: 'App\Modules\AERP\Controller\AERPSalesOrdersController'
  type:      annotation

AERPSalesDeliveryNotes:
  resource: 'App\Modules\AERP\Controller\AERPSalesDeliveryNotesController'
  type:      annotation

AERPSalesInvoices:
  resource: 'App\Modules\AERP\Controller\AERPSalesInvoicesController'
  type:      annotation

VehiclesVehicles:
  resource: 'App\Modules\Vehicles\Controller\VehiclesVehiclesController'
  type:      annotation

ERPSalesBudgets:
  resource: 'App\Modules\ERP\Controller\ERPSalesBudgetsController'
  type:      annotation
